---
abstract: unknown
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: libwww-hkp-perl
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 6.05
  Test::More: 0
  URI: 1.6
  URI::Escape: 3.31
version: 0.02
